---
.puppet-lint.rc:
  extra_disabled_lint_checks:
    - arrow_on_right_operand_line
.travis.yml:
  beaker_sets:
    - centos7-64
    - centos8-64
Rakefile:
  param_docs_pattern:
    - manifests/init.pp
